//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_02._01_System_for_organizing_conferences
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_YP_OrgConfTESTEntities : DbContext
    {
        public DB_YP_OrgConfTESTEntities()
            : base("name=DB_YP_OrgConfTESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Активности> Активности { get; set; }
        public virtual DbSet<АктивностиЖюри> АктивностиЖюри { get; set; }
        public virtual DbSet<Города> Города { get; set; }
        public virtual DbSet<Мероприятия> Мероприятия { get; set; }
        public virtual DbSet<МероприятияИнформационнаяБезопасность> МероприятияИнформационнаяБезопасность { get; set; }
        public virtual DbSet<Направления> Направления { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<РолиПользователей> РолиПользователей { get; set; }
        public virtual DbSet<Страны> Страны { get; set; }
    }
}
