//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_02._01_System_for_organizing_conferences
{
    using System;
    using System.Collections.Generic;
    
    public partial class АктивностиЖюри
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public АктивностиЖюри()
        {
            this.Активности = new HashSet<Активности>();
        }
    
        public int ID_АктивностьЖюри { get; set; }
        public string Активность { get; set; }
        public Nullable<int> Жюри_1 { get; set; }
        public Nullable<int> Жюри_2 { get; set; }
        public Nullable<int> Жюри_3 { get; set; }
        public Nullable<int> Жюри_4 { get; set; }
        public Nullable<int> Жюри_5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
        public virtual Пользователи Пользователи2 { get; set; }
        public virtual Пользователи Пользователи3 { get; set; }
        public virtual Пользователи Пользователи4 { get; set; }
    }
}
