//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_02._01_System_for_organizing_conferences
{
    using System;
    using System.Collections.Generic;
    
    public partial class Активности
    {
        public int ID_Активности { get; set; }
        public string Активность { get; set; }
        public Nullable<int> Мероприятие_ID { get; set; }
        public Nullable<int> День { get; set; }
        public Nullable<System.DateTime> Время_начала { get; set; }
        public Nullable<int> Модератор_ID { get; set; }
        public Nullable<int> АктивностиЖюри_ID { get; set; }
        public string описание { get; set; }
    
        public virtual АктивностиЖюри АктивностиЖюри { get; set; }
        public virtual МероприятияИнформационнаяБезопасность МероприятияИнформационнаяБезопасность { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
