//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_02._01_System_for_organizing_conferences
{
    using System;
    using System.Collections.Generic;
    
    public partial class МероприятияИнформационнаяБезопасность
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public МероприятияИнформационнаяБезопасность()
        {
            this.Активности = new HashSet<Активности>();
            this.РолиПользователей = new HashSet<РолиПользователей>();
        }
    
        public int ID_событие { get; set; }
        public string событие { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public Nullable<int> дни { get; set; }
        public Nullable<int> город { get; set; }
        public Nullable<int> мероприятия_ID { get; set; }
        public string описание { get; set; }
        public string логотип { get; set; }
        public Nullable<int> направление_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        public virtual Города Города { get; set; }
        public virtual Мероприятия Мероприятия { get; set; }
        public virtual Направления Направления { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РолиПользователей> РолиПользователей { get; set; }
    }
}
