//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_02._01_System_for_organizing_conferences
{
    using System;
    using System.Collections.Generic;
    
    public partial class Направления
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Направления()
        {
            this.МероприятияИнформационнаяБезопасность = new HashSet<МероприятияИнформационнаяБезопасность>();
            this.РолиПользователей = new HashSet<РолиПользователей>();
        }
    
        public int ID_направление { get; set; }
        public string направление { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<МероприятияИнформационнаяБезопасность> МероприятияИнформационнаяБезопасность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РолиПользователей> РолиПользователей { get; set; }
    }
}
