//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_02._01_System_for_organizing_conferences
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Активности = new HashSet<Активности>();
            this.АктивностиЖюри = new HashSet<АктивностиЖюри>();
            this.АктивностиЖюри1 = new HashSet<АктивностиЖюри>();
            this.АктивностиЖюри2 = new HashSet<АктивностиЖюри>();
            this.АктивностиЖюри3 = new HashSet<АктивностиЖюри>();
            this.АктивностиЖюри4 = new HashSet<АктивностиЖюри>();
            this.РолиПользователей = new HashSet<РолиПользователей>();
        }
    
        public int ID_пользователи { get; set; }
        public Nullable<int> роли_ID { get; set; }
        public string фио { get; set; }
        public string почта { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public Nullable<int> страны_ID { get; set; }
        public string телефон { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
        public string пол { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АктивностиЖюри> АктивностиЖюри { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АктивностиЖюри> АктивностиЖюри1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АктивностиЖюри> АктивностиЖюри2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АктивностиЖюри> АктивностиЖюри3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АктивностиЖюри> АктивностиЖюри4 { get; set; }
        public virtual Роли Роли { get; set; }
        public virtual Страны Страны { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РолиПользователей> РолиПользователей { get; set; }
    }
}
