//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_02._01_System_for_organizing_conferences
{
    using System;
    using System.Collections.Generic;
    
    public partial class РолиПользователей
    {
        public int ID_РолиПользователи { get; set; }
        public Nullable<int> пользователи_ID { get; set; }
        public Nullable<int> роли_ID { get; set; }
        public Nullable<int> направление_ID { get; set; }
        public Nullable<int> мероприятие_ID { get; set; }
    
        public virtual Мероприятия Мероприятия { get; set; }
        public virtual МероприятияИнформационнаяБезопасность МероприятияИнформационнаяБезопасность { get; set; }
        public virtual Направления Направления { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
